#!/bin/bash

# Helper for searching code base without searching through external code

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
    cd $DIR
    exec ack "$@" \
        --ignore-directory .tox \
        --ignore-directory dist \
        --ignore-directory build \
        --ignore-directory lifx_photons_core.egg-info \
        --ignore-directory tools \
        --ignore-directory docs/.sphinx-build \
        --ignore-directory docs/res \
        --ignore-directory docs/gh-pages 
)
